variables:
  myvar: debug

trigger:
- stack*

pool:
  - name: $(pool_name)

steps:
- script: echo Hello, world!
  displayName: 'say helloworld'

- script: |
    echo $(pool_name)
  displayName: 'display the pool name'