#
# Will deploy openshift in different Use Cases.
# Needs some variables to be set in azure pipelines Web IHM to work.
#   azs_pool_name: Azure Pipelines pool to use with Azure Stack (VM must be able to reach your Azure Stack)
#   azs_arm_endpoint: The ResourceManagerUrl in the Azure Stack (example: https://management.local.azurestack.external)
#   azs_suffix_storage_endpoint: use an endpoint for your Azure Stack (example: local.azurestack.external)
#   azs_suffix_keyvault_dns: use an endpoint for your Azure Stack (example: .vault.local.azurestack.external)
trigger:
- stack311*

stages:
- stage: Deploy on Azure Stack
  jobs:
  - job: OCP with 1 Master LB and self signed certificates
    pool: $(azs_pool_name)
    steps:
    - script: |
        az cloud register -n AzureStackUser \
          --endpoint-resource-manager "$(azs_arm_endpoint)" \
          --suffix-storage-endpoint "$(azs_suffix_storage_endpoint)" \
          --suffix-keyvault-dns "$(azs_suffix_keyvault_dns)"
      displayName: az cloud registering Azure Stack
